services:
  _defaults:
    autoconfigure: true
    public: false
    autowire: true

  Rinsvent\Data2DTODoctrineDocumentBundle\Service\:
    resource: '../../../src/Service'

  _instanceof:
    Rinsvent\TransformerBundle\Service\AbstractTransformer:
      tags: [ 'rinsvent.transformer.transformer' ]
